export const categoryActionTypes = {
  CATEGORY_REQUEST_INITIATED: 'CATEGORY_REQUEST_INITIATED',
  CATEGORY_FIND_ALL_REQUEST: 'CATEGORY_FIND_ALL_REQUEST',
  CATEGORY_FIND_ALL_REQUEST_SUCCEED: 'CATEGORY_FIND_ALL_REQUEST_SUCCEED',
  CATEGORY_FIND_ALL_REQUEST_FAILED: 'CATEGORY_FIND_ALL_REQUEST_FAILED',
  CATEGORY_FIND_BY_ID_REQUEST: 'CATEGORY_FIND_ALL_REQUEST',
  CATEGORY_FIND_BY_ID_REQUEST_SUCCEED: 'CATEGORY_FIND_ALL_REQUEST_SUCCEED',
  CATEGORY_FIND_BY_ID_REQUEST_FAILED: 'CATEGORY_FIND_ALL_REQUEST_FAILED',
  CATEGORY_QUERY_REQUEST: 'CATEGORY_QUERY_REQUEST',
  CATEGORY_QUERY_REQUEST_SUCCEED: 'CATEGORY_QUERY_REQUEST_SUCCEED',
  CATEGORY_QUERY_REQUEST_FAILED: 'CATEGORY_QUERY_REQUEST_FAILED',
};

export const itemActionTypes = {
  ITEM_REQUEST_INITIATED: 'ITEM_REQUEST_INITIATED',
  ITEM_FIND_ALL_REQUEST: 'ITEM_FIND_ALL_REQUEST',
  ITEM_FIND_ALL_REQUEST_SUCCEED: 'ITEM_FIND_ALL_REQUEST_SUCCEED',
  ITEM_FIND_ALL_REQUEST_FAILED: 'ITEM_FIND_ALL_REQUEST_FAILED',
  ITEM_FIND_BY_ID_REQUEST: 'ITEM_FIND_ALL_REQUEST',
  ITEM_FIND_BY_ID_REQUEST_SUCCEED: 'ITEM_FIND_ALL_REQUEST_SUCCEED',
  ITEM_FIND_BY_ID_REQUEST_FAILED: 'ITEM_FIND_ALL_REQUEST_FAILED',
  ITEM_QUERY_REQUEST: 'ITEM_QUERY_REQUEST',
  ITEM_QUERY_REQUEST_SUCCEED: 'ITEM_QUERY_REQUEST_SUCCEED',
  ITEM_QUERY_REQUEST_FAILED: 'ITEM_QUERY_REQUEST_FAILED',
};
